### ISSUE TITLE
Nothing happens after I enter my twitter handle

### ISSUE THREAD

**Issue by mohitmunjal** [huangy22/NewsRecommender#1]
As soon as I put my twitter handle, nothing happens after that.

**Comment by huangy22** [comment]
@mohitmunjal This issue is actually due to the limitation of the database for this project. As this is only a proof-of-concept project, I only collected a small subset of twitter user information in the database for this app. The users that are recorded in the database are those who retweeted any news published in three different News Publishers (New York Times, Washington Post, and Bloomberg) during two weeks in the summer of 2017. I'm sorry that your twitter handle seems to be not in the list and therefore you can only see a random recommendation that are based on the overall popularity of the news articles. Anyway, thank you so much for the feedback and interest in this project!
